dict = {}

dict['Samridhi'] = "sam325cc"
dict['Ayush'] = "animelove"
dict['Gauri'] = "arch100"
dict['Kshitij'] = "kstgh321"
dict['Obama'] = "expres32"
dict['Biden'] = "currentpres"
dict['Sanket'] = "sanket323"
dict['Milind'] = "mumbailove"
dict['Radha'] = "mangos19"
dict['Rutuja'] = "meowiam"
dict['Vaibhav'] = "beatdancer"
dict['Vivek'] = "delhiboy"
dict['Priyanshu'] = "fboycoder"
dict['Shivanshu'] = "shivshakti"
dict['Messi'] = "goatno1"
dict['Ronaldo'] = "goatno2"
dict['Harry'] = "onedlover"
dict['Nick'] = "broband"
dict['Trump'] = "bantwitter"
dict['zayn'] = "gigihadid"
dict['Vaibhavi'] = "lokesh33"
dict['Taylor'] = "delicasy"
dict['Snigdha'] = "shivbro"
dict['Anushka'] = "classical"
dict['Ashutosh'] = "bdhaios"

def auth_users():
    return dict
